//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 07:54:38 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://teja.vin.com/service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vin.teja.service;
